version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-dev
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000" # Vite's default port

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-dev
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000" # Your backend port
